const { GoogleGenerativeAI } = require("@google/generative-ai");

/**
 * Initializes the Gemini API SDK based strictly on the backend .env configuration.
 */
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

/**
 * Executes a code analysis using gemini-1.5-flash mathematically engineered to return
 * only the explicitly requested 7-key JSON structure.
 * 
 * @param {string} code - The student's submitted code string.
 * @param {string} language - The programming language the code was written in.
 * @returns {Promise<Object>} An aggregated assessment structured strictly to JSON bounds.
 */
async function analyzeCodeWithAI(code, language) {
  try {
    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    // The rigorous prompt locking the output completely into native JSON formatting
    const prompt = `You are an expert ${language} coding instructor reviewing a student's submission.

Analyze the following code:
${code}

Return your feedback STRICTLY in the following raw JSON format with NO markdown wrapping, NO backticks, and NO accompanying text. Ensure all fields are valid strings:
{
  "timeComplexity": "string explaining time complexity",
  "spaceComplexity": "string explaining space complexity",
  "readability": "string explaining code readability",
  "naming": "string with variable naming suggestions",
  "optimization": "string with optimization suggestions",
  "bugs": "string defining possible bugs/edge cases",
  "bestPractices": "string explaining any relevant best practices"
}`;

    // Fire the Gemini model utilizing an asynchronous execution race against a 15-second timeout limit
    const requestPromise = model.generateContent(prompt);
    
    const timeoutPromise = new Promise((_, reject) => {
      setTimeout(() => reject(new Error("AI Analysis request timed out")), 15000);
    });

    const result = await Promise.race([requestPromise, timeoutPromise]);
    const responseText = result.response.text();

    // Clean any accidental markdown code blocks generated by the AI
    const cleanedText = responseText.replace(/```json/i, '').replace(/```/g, '').trim();

    return JSON.parse(cleanedText);
    
  } catch (error) {
    console.error("AI Analysis Execution Error:", error);
    throw error;
  }
}

module.exports = {
  analyzeCodeWithAI
};
